# Generated by Django 5.0.2 on 2024-02-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="title",
            new_name="name",
        ),
    ]
