# Generated by Django 5.0.2 on 2024-03-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('startlocation', models.TextField()),
                ('endlocation', models.TextField()),
                ('numPassengers', models.IntegerField()),
                ('rideTime', models.TimeField()),
                ('identifier', models.IntegerField()),
            ],
        ),
    ]
