# Generated by Django 5.0.2 on 2024-03-26 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='rideTime',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
