# Generated by Django 5.0.2 on 2024-03-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0002_alter_ride_ridetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='identifier',
            field=models.IntegerField(default=9526),
        ),
        migrations.AlterField(
            model_name='ride',
            name='rideTime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
