# Generated by Django 5.0.2 on 2024-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0003_alter_ride_identifier_alter_ride_ridetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='isEmergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ride',
            name='identifier',
            field=models.IntegerField(default=7418),
        ),
    ]
