# Generated by Django 5.0.2 on 2024-04-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0004_ride_isemergency_alter_ride_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='identifier',
            field=models.IntegerField(default=3062),
        ),
    ]
