# Generated by Django 5.0.2 on 2024-04-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_app', '0005_alter_ride_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='identifier',
            field=models.IntegerField(default=3018),
        ),
    ]
